import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import React, { useContext, createContext,useEffect, useRef, useState } from 'react'
import styles from '../styles/Home.module.css'
import Boot from '../components/Boot'
import Logs from '../components/Logs'
import Login from '../components/Login'
import Home from '../components/Home'

export const PageContext = createContext<any>(0)

const Index: NextPage = () => {
  const [page, setPage] = useState(0)
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    
      </Head>

      <PageContext.Provider value={{ page, setPage }}>
      <main>
        {page === 0 && <Boot />}
        {page === 1 && <Logs />}
        {page === 2 && <Login />}
        {page === 3 && <Home />}
      </main>
      </PageContext.Provider>
    </div>
  )
}

export default Index
